//(c) Copyright Modaal.dev 2026

import RxSwift

public enum FieldPath {
  case documentId
  case fields([String])

  public static func field(_ name: String) -> FieldPath {
    .fields([name])
  }
}

public enum Filter {
  case equalTo(FieldPath, value: Any)
  case notEqualTo(FieldPath, value: Any)
  case greaterThan(FieldPath, value: Any)
  case greaterThanOrEqualTo(FieldPath, value: Any)
  case lessThan(FieldPath, value: Any)
  case lessThanOrEqualTo(FieldPath, value: Any)
  case arrayContains(FieldPath, value: Any)
  case arrayContainsAny(FieldPath, values: [Any])
  case fieldIn(FieldPath, value: [Any])
  case fieldNotIn(FieldPath, values: [Any])
  case any([Filter])
  case all([Filter])
}

/// sourcery: CreateMock
public protocol QueryiableCollectionStoring {
  func filter(_ filter: Storage.Filter) -> QueryiableCollectionStoring
  func order(by field: Storage.FieldPath, descending value: Bool) -> QueryiableCollectionStoring
  func limit(to value: Int) -> QueryiableCollectionStoring
  func limit(toLast value: Int) -> QueryiableCollectionStoring

  func get() -> Single<[String: DocumentStoring]>
  func list() -> Observable<[String: DocumentStoring]>

  // MARK: - Aggregation
  func count() -> Single<Int>
}

/// sourcery: CreateMock
public protocol CollectionStoring: QueryiableCollectionStoring {
  var collectionId: String { get }

  // MARK: - Document access

  /// Create a new document with the autogenerated documentId.
  func document() -> DocumentStoring

  /// Create a document reference.
  /// The document reference is created locallly.
  /// Until the document is queried, or updated, remote database is not modified.
  func document(_ path: String) -> DocumentStoring
}
